= Welcome to Workload Discovery on AWS

Monitoring your Amazon Web Services (AWS) Cloud workloads is key to maintaining operational health and efficiency. However, keeping track of the AWS resources and the relationships between them can be a challenge. Workload Discovery on AWS is a visualization tool that automatically generates architecture diagrams of AWS Cloud workloads. You can use the solution to build, customize, and share detailed workload visualizations based on live data from AWS.

This solution works by maintaining an inventory of the AWS resources across your accounts and Regions, mapping relationships between them, and displaying them in a web user interface (web UI). When making changes to a resource, Workload Discovery on AWS saves you time by providing a link to the resource in the AWS Management Console.

== How to use this website

The documentation for Workload Discovery on AWS is currently divided across two websites:

* The https://docs.aws.amazon.com/solutions/latest/workload-discovery-on-aws/[Implementation Guide] contains instructions for how to install the solution as well as design, cost, and security information you should be aware of to run the solution.

* This website contains information for operating Workload Discovery on AWS after you have installed the solution including how to use its various features and troubleshooting guides.

== Getting Started

Workload Discovery on AWS is an AWS Solution that you deploy into your own AWS account. To get started deploying the solution, refer to the https://docs.aws.amazon.com/solutions/latest/workload-discovery-on-aws/automated-deployment.html[Automated Deployment] section of the https://docs.aws.amazon.com/solutions/latest/workload-discovery-on-aws/[Implementation Guide].