---

site:
  title: Workload Discovery on AWS
  start_page: workload-discovery-on-aws::index.adoc
content:
  sources:
    - url: ../
      branches: HEAD
      start_path: docs/
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
