exports.vpcInput = [
    {
        "properties": {
            "configurationItemStatus": "OK",
            "resourceId": "vpc-88f114f1",
            "configuration": "{\"cidrBlock\":\"172.31.0.0/16\",\"dhcpOptionsId\":\"dopt-fdacf89b\",\"state\":\"available\",\"vpcId\":\"vpc-88f114f1\",\"ownerId\":\"XXXXXXXXXXXX\",\"instanceTenancy\":\"default\",\"ipv6CidrBlockAssociationSet\":[],\"cidrBlockAssociationSet\":[{\"associationId\":\"vpc-cidr-assoc-b57b76de\",\"cidrBlock\":\"172.31.0.0/16\",\"cidrBlockState\":{\"state\":\"associated\",\"statusMessage\":null}}],\"isDefault\":true,\"tags\":[]}",
            "title": "vpc-88f114f1",
            "availabilityZone": "Multiple Availability Zones",
            "loggedInURL": "https://eu-west-1.console.aws.amazon.com/vpc/v2/home?region=eu-west-1#vpcs:sort=VpcId",
            "loginURL": "https://XXXXXXXXXXXX.signin.aws.amazon.com/console/vpc?region=eu-west-1#vpcs:sort=VpcId",
            "vpcId": "vpc-88f114f1",
            "relatedEvents": "[]",
            "state": "\"available\"",
            "arn": "arn:aws:ec2:eu-west-1:XXXXXXXXXXXX:vpc/vpc-88f114f1",
            "instanceTenancy": "default",
            "awsRegion": "eu-west-1",
            "supplementaryConfiguration": "{}",
            "configurationItemMD5Hash": "",
            "cidrBlock": "172.31.0.0/16",
            "version": "1.3",
            "configurationItemCaptureTime": "2019-12-12T21:09:52.777Z",
            "tags": "{}",
            "accountId": "XXXXXXXXXXXX",
            "configurationStateId": "XXXXXXXXXXXX",
            "isDefault": "true",
            "dhcpOptionsId": "dopt-fdacf89b",
            "resourceType": "AWS::EC2::VPC"
        },
        "perspectiveBirthDate": "2019-12-12T21:11:21.992Z",
        "id": "b9d7a6f27482f7dbb97df1b7e792d346",
        "label": "AWS::EC2::VPC"
    },
    {
        "properties": {
            "configurationItemStatus": "OK",
            "resourceId": "vpc-0d1489acdc666462d",
            "configuration": "{\"cidrBlock\":\"10.0.0.0/16\",\"dhcpOptionsId\":\"dopt-fdacf89b\",\"state\":\"available\",\"vpcId\":\"vpc-0d1489acdc666462d\",\"ownerId\":\"XXXXXXXXXXXX\",\"instanceTenancy\":\"default\",\"ipv6CidrBlockAssociationSet\":[],\"cidrBlockAssociationSet\":[{\"associationId\":\"vpc-cidr-assoc-025cffec99772bb85\",\"cidrBlock\":\"10.0.0.0/16\",\"cidrBlockState\":{\"state\":\"associated\",\"statusMessage\":null}}],\"isDefault\":false,\"tags\":[{\"key\":\"aws:cloudformation:stack-name\",\"value\":\"aws-perspective-eu-west-1-VpcStack-XNWX659JE84X\"},{\"key\":\"aws:cloudformation:logical-id\",\"value\":\"VPC\"},{\"key\":\"aws:cloudformation:stack-id\",\"value\":\"arn:aws:cloudformation:eu-west-1:XXXXXXXXXXXX:stack/aws-perspective-eu-west-1-VpcStack-XNWX659JE84X/54bd4340-11f9-11ea-bec0-0224adcab7c8\"},{\"key\":\"Application\",\"value\":\"aws-perspective-eu-west-1-VpcStack-XNWX659JE84X\"},{\"key\":\"Network\",\"value\":\"Public\"},{\"key\":\"AppName\",\"value\":\"aws-perspective\"}]}",
            "title": "vpc-0d1489acdc666462d",
            "availabilityZone": "Multiple Availability Zones",
            "loggedInURL": "https://eu-west-1.console.aws.amazon.com/vpc/v2/home?region=eu-west-1#vpcs:sort=VpcId",
            "loginURL": "https://XXXXXXXXXXXX.signin.aws.amazon.com/console/vpc?region=eu-west-1#vpcs:sort=VpcId",
            "vpcId": "vpc-0d1489acdc666462d",
            "relatedEvents": "[]",
            "state": "\"available\"",
            "arn": "arn:aws:ec2:eu-west-1:XXXXXXXXXXXX:vpc/vpc-0d1489acdc666462d",
            "instanceTenancy": "default",
            "awsRegion": "eu-west-1",
            "supplementaryConfiguration": "{}",
            "configurationItemMD5Hash": "",
            "cidrBlock": "10.0.0.0/16",
            "version": "1.3",
            "configurationItemCaptureTime": "2019-12-05T15:32:29.119Z",
            "tags": "{\"AppName\":\"aws-perspective\",\"Application\":\"aws-perspective-eu-west-1-VpcStack-XNWX659JE84X\",\"Network\":\"Public\",\"aws:cloudformation:logical-id\":\"VPC\",\"aws:cloudformation:stack-id\":\"arn:aws:cloudformation:eu-west-1:XXXXXXXXXXXX:stack/aws-perspective-eu-west-1-VpcStack-XNWX659JE84X/54bd4340-11f9-11ea-bec0-0224adcab7c8\",\"aws:cloudformation:stack-name\":\"aws-perspective-eu-west-1-VpcStack-XNWX659JE84X\"}",
            "accountId": "XXXXXXXXXXXX",
            "configurationStateId": "XXXXXXXXXXXX",
            "isDefault": "false",
            "dhcpOptionsId": "dopt-fdacf89b",
            "resourceType": "AWS::EC2::VPC"
        },
        "perspectiveBirthDate": "2019-12-11T12:11:25.283Z",
        "id": "e00f68f37185c3988a77219f77285936",
        "label": "AWS::EC2::VPC"
    }
]
