AWSTemplateFormatVersion: 2010-09-09

Description: AWS Perspective Cloudfront Distribution Stack

Parameters:
  AccessLogsBucket:
    Description: The bucket that contains the access logs for Perspective buckets.
    Type: String
  SecuredEdgeBucket:
    Type: String
    Description: The bucket where the zip files containing the source code for the SecuredEdge Lambda
  DeploymentBucketKey:
    Type: String
    Description: The key within the bucket that contains the source code zips

Resources:
  SecurityFunction:
    Type: AWS::CloudFront::Function
    Properties:
      AutoPublish: true
      Name:
        !Sub
          - HSTS-FUNCTION-${StackBit}
          - StackBit: !Select
            - 7
            - !Split
              - "-"
              - !Ref AWS::StackName

      FunctionConfig:
        Comment: Security Headers
        Runtime: cloudfront-js-1.0
      'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location : !Sub 's3://${SecuredEdgeBucket}/${DeploymentBucketKey}/cff-hsts.js'

  WebUIBucketReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: '{{resolve:ssm:WebUIBucketName:1}}'
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource:
              Fn::Sub:
                - arn:aws:s3:::${WebUIBucketName}/*
                - WebUIBucketName: '{{resolve:ssm:WebUIBucketName:1}}'
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - CloudFrontOriginAccessIdentity
                  - S3CanonicalUserId
          - Sid: HttpsOnly
            Action: '*'
            Effect: Deny
            Resource: 
              - Fn::Sub:                
                - arn:aws:s3:::${WebUIBucketName}
                - WebUIBucketName: '{{resolve:ssm:WebUIBucketName:1}}' 
              - Fn::Sub:                
                - arn:aws:s3:::${WebUIBucketName}/*
                - WebUIBucketName: '{{resolve:ssm:WebUIBucketName:1}}'              
            Principal: '*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: '{{resolve:ssm:WebUIBucketName:1}}'

  CloudFrontDistribution:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W70
            reason: 'If the distribution uses the CloudFront domain name such as d111111abcdef8.cloudfront.net (you set CloudFrontDefaultCertificate to true), CloudFront automatically sets the security policy to TLSv1 regardless of the value that you set here.'
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: '{{resolve:ssm:WebUIBucketRegionalDomainName:1}}'
            Id: perspective-origin
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Sub: origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        Enabled: true
        HttpVersion: http2
        Comment: The Distribution for the Perspective Web UI
        DefaultRootObject: index.html
        Logging:
          Bucket: !Sub ${AccessLogsBucket}.s3.amazonaws.com
          IncludeCookies: false
          Prefix: 'aws-perspective-ui'
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          TargetOriginId: perspective-origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
            - EventType: viewer-response
              FunctionARN: !GetAtt SecurityFunction.FunctionMetadata.FunctionARN
        PriceClass: PriceClass_All
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: TLSv1.1_2016

Outputs:

  WebUiUrl:
    Value: !Sub https://${CloudFrontDistribution.DomainName}
    Description: WebUI URL
