= Post-deployment tasks

After Workload Discovery on AWS has been successfully deployed, review the following post-deployment configuration tasks.

== Turn on Advanced security in Amazon Cognito

To turn on the Advanced security features for Amazon Cognito, follow the instructions on
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-advanced-security.html[Adding
Advanced Security to a User Pool] in the _Amazon Cognito Developer Guide_.

NOTE: There is an additional cost for activating Advanced security in Amazon Cognito.

== Create Amazon Cognito users

Workload Discovery on AWS uses Amazon Cognito to manage all users and authentication.
It creates a user for you during deployment and sends an email at the address provided with temporary credentials.

*To create additional users:*

. Sign in to the https://console.aws.amazon.com/cognito/[AWS Cognito
console].
. Choose Manage User Pools.
. Choose *perspective.*`+<+`_`+deployment-region+`_`+>+`*.userpool*.
. In the navigation pane, under *General Settings*, choose *Users and groups__.__*
. On the *Users* tab, choose *Create user*.
. On the *Create user* box, enter values for all required fields.
+
[cols=",,",options="header",]
|===
|Form Field |Required? |Description
|*Username* |Yes |The username that you will use to log in to Workload
Discovery on AWS.

|*Send an invitation* |Yes (email only) |When selected, sends a
notification as a reminder of the temporary password. Select *Email*
only. If you select *SMS (default)* an error message will be displayed,
but the user will still be created.

|*Temporary Password* |Yes |Enter a temporary password. The user will be
forced to change this when they log in to Workload Discovery on AWS for
the first time.

|*Phone Number* |No |Enter a phone number in international format, for
example, +44. Ensure *Mark phone number as verified?* box is selected.

|*Email* |Yes |Enter a valid email address. Ensure *Mark email as
verified?* box is selected.
|===
. Choose *Create* *user*.

Repeat this process to create as many users as you need.

NOTE: Every user will have the same level of access to resources discovered.
We recommend provisioning a separate deployment of Workload Discovery on AWS for accounts that contain sensitive workloads or data.
This allows you to restrict access to only the users that need it.

